package miniprojet_cadenas_chiera;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author julie
 */
public class Interface extends javax.swing.JFrame {
    private Cadenas jeu = new Cadenas(4, 5); // 4 chiffres, 5 tentatives

    public Interface() {
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texte_intro = new javax.swing.JLabel();
        up_chiffre_1 = new javax.swing.JButton();
        up_chiffre_2 = new javax.swing.JButton();
        up_chiffre_3 = new javax.swing.JButton();
        up_chiffre_4 = new javax.swing.JButton();
        texte_chiffre_0 = new javax.swing.JLabel();
        texte_chiffre_1 = new javax.swing.JLabel();
        texte_chiffre_2 = new javax.swing.JLabel();
        texte_chiffre_3 = new javax.swing.JLabel();
        down_chiffre_1 = new javax.swing.JButton();
        down_chiffre_2 = new javax.swing.JButton();
        down_chiffre_3 = new javax.swing.JButton();
        down_chiffre_4 = new javax.swing.JButton();
        bouton_tester = new javax.swing.JButton();
        texte_lbl_nb_chiffres_exacts = new javax.swing.JLabel();
        texte_nb_chiffres_exacts = new javax.swing.JLabel();
        texte_lbl_nb_chiffres_haut = new javax.swing.JLabel();
        texte_nb_chiffres_haut = new javax.swing.JLabel();
        texte_lbl_nb_chiffres_bas = new javax.swing.JLabel();
        texte_nb_chiffres_bas = new javax.swing.JLabel();
        texte_score = new javax.swing.JLabel();
        texte_tentatives = new javax.swing.JLabel();
        bouton_recommencer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texte_intro.setBackground(new java.awt.Color(255, 255, 255));
        texte_intro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        texte_intro.setForeground(new java.awt.Color(255, 51, 204));
        texte_intro.setText("Trouver le bon code en moins de 5 Tentatives !");
        getContentPane().add(texte_intro, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 6, -1, -1));

        up_chiffre_1.setBackground(new java.awt.Color(255, 0, 153));
        up_chiffre_1.setText("^");
        up_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up_chiffre_1ActionPerformed(evt);
            }
        });
        getContentPane().add(up_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 60, 20));

        up_chiffre_2.setBackground(new java.awt.Color(255, 0, 153));
        up_chiffre_2.setText("^");
        up_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up_chiffre_2ActionPerformed(evt);
            }
        });
        getContentPane().add(up_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 60, 20));

        up_chiffre_3.setBackground(new java.awt.Color(255, 0, 153));
        up_chiffre_3.setText("^");
        up_chiffre_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up_chiffre_3ActionPerformed(evt);
            }
        });
        getContentPane().add(up_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 60, 20));

        up_chiffre_4.setBackground(new java.awt.Color(255, 0, 153));
        up_chiffre_4.setText("^");
        up_chiffre_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                up_chiffre_4ActionPerformed(evt);
            }
        });
        getContentPane().add(up_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 60, 20));

        texte_chiffre_0.setBackground(new java.awt.Color(255, 204, 255));
        texte_chiffre_0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texte_chiffre_0.setText("0");
        texte_chiffre_0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(texte_chiffre_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 60, 60));

        texte_chiffre_1.setBackground(new java.awt.Color(255, 204, 255));
        texte_chiffre_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texte_chiffre_1.setText("0");
        texte_chiffre_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(texte_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 60, 60));

        texte_chiffre_2.setBackground(new java.awt.Color(255, 204, 255));
        texte_chiffre_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texte_chiffre_2.setText("0");
        texte_chiffre_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(texte_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 60, 60));

        texte_chiffre_3.setBackground(new java.awt.Color(255, 204, 255));
        texte_chiffre_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texte_chiffre_3.setText("0");
        texte_chiffre_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(texte_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 60, 60));

        down_chiffre_1.setBackground(new java.awt.Color(255, 0, 153));
        down_chiffre_1.setText("v");
        down_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                down_chiffre_1ActionPerformed(evt);
            }
        });
        getContentPane().add(down_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 60, 20));

        down_chiffre_2.setBackground(new java.awt.Color(255, 0, 153));
        down_chiffre_2.setText("v");
        down_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                down_chiffre_2ActionPerformed(evt);
            }
        });
        getContentPane().add(down_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 60, 20));

        down_chiffre_3.setBackground(new java.awt.Color(255, 0, 153));
        down_chiffre_3.setText("v");
        down_chiffre_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                down_chiffre_3ActionPerformed(evt);
            }
        });
        getContentPane().add(down_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 60, 20));

        down_chiffre_4.setBackground(new java.awt.Color(255, 0, 153));
        down_chiffre_4.setText("v");
        down_chiffre_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                down_chiffre_4ActionPerformed(evt);
            }
        });
        getContentPane().add(down_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 60, 20));

        bouton_tester.setBackground(new java.awt.Color(255, 0, 153));
        bouton_tester.setText("TESTER");
        bouton_tester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_testerActionPerformed(evt);
            }
        });
        getContentPane().add(bouton_tester, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, -1));

        texte_lbl_nb_chiffres_exacts.setText("Nombre de chiffres exacts : ");
        getContentPane().add(texte_lbl_nb_chiffres_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        texte_nb_chiffres_exacts.setText("0");
        getContentPane().add(texte_nb_chiffres_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, -1));

        texte_lbl_nb_chiffres_haut.setText("Nombre de chiffres trop hauts :");
        getContentPane().add(texte_lbl_nb_chiffres_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        texte_nb_chiffres_haut.setText("0");
        getContentPane().add(texte_nb_chiffres_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));

        texte_lbl_nb_chiffres_bas.setText("Nombre de chiffres trop bas :");
        getContentPane().add(texte_lbl_nb_chiffres_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        texte_nb_chiffres_bas.setText("0");
        getContentPane().add(texte_nb_chiffres_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, -1, -1));

        texte_score.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texte_score.setText("0 sur 5");
        texte_score.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(texte_score, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 70, 50));

        texte_tentatives.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texte_tentatives.setText("Tentatives");
        getContentPane().add(texte_tentatives, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 70, -1));

        bouton_recommencer.setBackground(new java.awt.Color(255, 0, 153));
        bouton_recommencer.setText("Recommencer");
        bouton_recommencer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bouton_recommencerActionPerformed(evt);
            }
        });
        getContentPane().add(bouton_recommencer, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void down_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_2ActionPerformed
        int val = Integer.parseInt(texte_chiffre_1.getText());
        val = (val + 9) % 10; // boucle inverse : 0 → 9
        texte_chiffre_1.setText(String.valueOf(val));
    }//GEN-LAST:event_down_chiffre_2ActionPerformed

    private void up_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_1ActionPerformed
        int val = Integer.parseInt(texte_chiffre_0.getText());
        val = (val + 1) % 10; // boucle après 9 → revient à 0
        texte_chiffre_0.setText(String.valueOf(val));
    }//GEN-LAST:event_up_chiffre_1ActionPerformed

    private void up_chiffre_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_4ActionPerformed
        int val = Integer.parseInt(texte_chiffre_3.getText());
        val = (val + 1) % 10; // boucle après 9 → revient à 0
        texte_chiffre_3.setText(String.valueOf(val));
    }//GEN-LAST:event_up_chiffre_4ActionPerformed

    private void up_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_2ActionPerformed
        int val = Integer.parseInt(texte_chiffre_1.getText());
        val = (val + 1) % 10; // boucle après 9 → revient à 0
        texte_chiffre_1.setText(String.valueOf(val));
    }//GEN-LAST:event_up_chiffre_2ActionPerformed

    private void up_chiffre_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_3ActionPerformed
         int val = Integer.parseInt(texte_chiffre_2.getText());
        val = (val + 1) % 10; // boucle après 9 → revient à 0
        texte_chiffre_2.setText(String.valueOf(val));
    }//GEN-LAST:event_up_chiffre_3ActionPerformed

    private void down_chiffre_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_3ActionPerformed
        int val = Integer.parseInt(texte_chiffre_2.getText());
        val = (val + 9) % 10; // boucle inverse : 0 → 9
        texte_chiffre_2.setText(String.valueOf(val));
    }//GEN-LAST:event_down_chiffre_3ActionPerformed

    private void down_chiffre_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_4ActionPerformed
        int val = Integer.parseInt(texte_chiffre_3.getText());
        val = (val + 9) % 10; // boucle inverse : 0 → 9
        texte_chiffre_3.setText(String.valueOf(val));  
    }//GEN-LAST:event_down_chiffre_4ActionPerformed

    private void down_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_1ActionPerformed
        int val = Integer.parseInt(texte_chiffre_0.getText());
        val = (val + 9) % 10; // boucle inverse : 0 → 9
        texte_chiffre_0.setText(String.valueOf(val));
    }//GEN-LAST:event_down_chiffre_1ActionPerformed

    private void bouton_testerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_testerActionPerformed
        // Construire la proposition du joueur
        String prop =
            texte_chiffre_0.getText() +
            texte_chiffre_1.getText() +
            texte_chiffre_2.getText() +
            texte_chiffre_3.getText();

        try {
            // Appel à la classe métier
            Cadenas.Resultat r = jeu.evaluer(prop);

            // Afficher les résultats
            texte_nb_chiffres_exacts.setText(String.valueOf(r.exact));
            texte_nb_chiffres_haut.setText(String.valueOf(r.tropHaut));
            texte_nb_chiffres_bas.setText(String.valueOf(r.tropBas));

            // Mettre à jour le compteur d'essais
            texte_score.setText(jeu.getTentativeCourante() + " sur " + jeu.getMaxTentatives());

            // Vérifier si fini
            if (jeu.getEtat() == Cadenas.Etat.GAGNE) {
                texte_intro.setText("BRAVO, vous avez gagné !");
                bouton_tester.setEnabled(false);
            }
            else if (jeu.getEtat() == Cadenas.Etat.PERDU) {
                texte_intro.setText("Perdu ! Le code était : " + jeu.getSecret());
                bouton_tester.setEnabled(false);
            }

        }
        catch (Exception e) {
            texte_intro.setText("Erreur : " + e.getMessage());
        }
    }//GEN-LAST:event_bouton_testerActionPerformed

    private void bouton_recommencerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_recommencerActionPerformed
        // Réinitialise le jeu
        jeu.reset();

        // Réinitialise l’affichage
        texte_chiffre_0.setText("0");
        texte_chiffre_1.setText("0");
        texte_chiffre_2.setText("0");
        texte_chiffre_3.setText("0");

        texte_nb_chiffres_exacts.setText("0");
        texte_nb_chiffres_haut.setText("0");
        texte_nb_chiffres_bas.setText("0");

        texte_score.setText("0 sur " + jeu.getMaxTentatives());
        texte_intro.setText("Trouver le bon code en moins de 5 Tentatives !");

        bouton_tester.setEnabled(true);
    }//GEN-LAST:event_bouton_recommencerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interface().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouton_recommencer;
    private javax.swing.JButton bouton_tester;
    private javax.swing.JButton down_chiffre_1;
    private javax.swing.JButton down_chiffre_2;
    private javax.swing.JButton down_chiffre_3;
    private javax.swing.JButton down_chiffre_4;
    private javax.swing.JLabel texte_chiffre_0;
    private javax.swing.JLabel texte_chiffre_1;
    private javax.swing.JLabel texte_chiffre_2;
    private javax.swing.JLabel texte_chiffre_3;
    private javax.swing.JLabel texte_intro;
    private javax.swing.JLabel texte_lbl_nb_chiffres_bas;
    private javax.swing.JLabel texte_lbl_nb_chiffres_exacts;
    private javax.swing.JLabel texte_lbl_nb_chiffres_haut;
    private javax.swing.JLabel texte_nb_chiffres_bas;
    private javax.swing.JLabel texte_nb_chiffres_exacts;
    private javax.swing.JLabel texte_nb_chiffres_haut;
    private javax.swing.JLabel texte_score;
    private javax.swing.JLabel texte_tentatives;
    private javax.swing.JButton up_chiffre_1;
    private javax.swing.JButton up_chiffre_2;
    private javax.swing.JButton up_chiffre_3;
    private javax.swing.JButton up_chiffre_4;
    // End of variables declaration//GEN-END:variables

}
