/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author julie
 */
public class GameWindow extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GameWindow.class.getName());

    /**
     * Creates new form GameWindow
     */
    public GameWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(6, 6));

        jButton1.setBackground(new java.awt.Color(255, 204, 255));
        jButton1.setForeground(new java.awt.Color(255, 231, 255));
        jButton1.setText("jButton1");
        getContentPane().add(jButton1);

        jButton2.setText("jButton1");
        getContentPane().add(jButton2);

        jButton3.setBackground(new java.awt.Color(255, 204, 255));
        jButton3.setForeground(new java.awt.Color(255, 231, 255));
        jButton3.setText("jButton1");
        getContentPane().add(jButton3);

        jButton4.setText("jButton1");
        getContentPane().add(jButton4);

        jButton5.setBackground(new java.awt.Color(255, 204, 255));
        jButton5.setForeground(new java.awt.Color(255, 231, 255));
        jButton5.setText("jButton1");
        getContentPane().add(jButton5);

        jButton6.setText("jButton1");
        getContentPane().add(jButton6);

        jButton7.setText("jButton1");
        getContentPane().add(jButton7);

        jButton8.setBackground(new java.awt.Color(255, 204, 255));
        jButton8.setForeground(new java.awt.Color(255, 231, 255));
        jButton8.setText("jButton1");
        getContentPane().add(jButton8);

        jButton9.setText("jButton1");
        getContentPane().add(jButton9);

        jButton10.setBackground(new java.awt.Color(255, 204, 255));
        jButton10.setForeground(new java.awt.Color(255, 231, 255));
        jButton10.setText("jButton1");
        getContentPane().add(jButton10);

        jButton11.setText("jButton1");
        getContentPane().add(jButton11);

        jButton12.setBackground(new java.awt.Color(255, 204, 255));
        jButton12.setForeground(new java.awt.Color(255, 231, 255));
        jButton12.setText("jButton1");
        getContentPane().add(jButton12);

        jButton13.setBackground(new java.awt.Color(255, 204, 255));
        jButton13.setForeground(new java.awt.Color(255, 231, 255));
        jButton13.setText("jButton1");
        getContentPane().add(jButton13);

        jButton14.setText("jButton1");
        getContentPane().add(jButton14);

        jButton15.setBackground(new java.awt.Color(255, 204, 255));
        jButton15.setForeground(new java.awt.Color(255, 231, 255));
        jButton15.setText("jButton1");
        getContentPane().add(jButton15);

        jButton16.setText("jButton1");
        getContentPane().add(jButton16);

        jButton17.setBackground(new java.awt.Color(255, 204, 255));
        jButton17.setForeground(new java.awt.Color(255, 231, 255));
        jButton17.setText("jButton1");
        getContentPane().add(jButton17);

        jButton18.setText("jButton1");
        getContentPane().add(jButton18);

        jButton19.setText("jButton1");
        getContentPane().add(jButton19);

        jButton20.setBackground(new java.awt.Color(255, 204, 255));
        jButton20.setForeground(new java.awt.Color(255, 231, 255));
        jButton20.setText("jButton1");
        getContentPane().add(jButton20);

        jButton21.setText("jButton1");
        getContentPane().add(jButton21);

        jButton22.setBackground(new java.awt.Color(255, 204, 255));
        jButton22.setForeground(new java.awt.Color(255, 231, 255));
        jButton22.setText("jButton1");
        getContentPane().add(jButton22);

        jButton23.setText("jButton1");
        getContentPane().add(jButton23);

        jButton24.setBackground(new java.awt.Color(255, 204, 255));
        jButton24.setForeground(new java.awt.Color(255, 231, 255));
        jButton24.setText("jButton1");
        getContentPane().add(jButton24);

        jButton25.setBackground(new java.awt.Color(255, 204, 255));
        jButton25.setForeground(new java.awt.Color(255, 231, 255));
        jButton25.setText("jButton1");
        getContentPane().add(jButton25);

        jButton26.setText("jButton1");
        getContentPane().add(jButton26);

        jButton27.setBackground(new java.awt.Color(255, 204, 255));
        jButton27.setForeground(new java.awt.Color(255, 231, 255));
        jButton27.setText("jButton1");
        getContentPane().add(jButton27);

        jButton28.setText("jButton1");
        getContentPane().add(jButton28);

        jButton29.setBackground(new java.awt.Color(255, 204, 255));
        jButton29.setForeground(new java.awt.Color(255, 231, 255));
        jButton29.setText("jButton1");
        getContentPane().add(jButton29);

        jButton30.setText("jButton1");
        getContentPane().add(jButton30);

        jButton31.setText("jButton1");
        getContentPane().add(jButton31);

        jButton32.setBackground(new java.awt.Color(255, 204, 255));
        jButton32.setForeground(new java.awt.Color(255, 231, 255));
        jButton32.setText("jButton1");
        getContentPane().add(jButton32);

        jButton33.setText("jButton1");
        getContentPane().add(jButton33);

        jButton34.setBackground(new java.awt.Color(255, 204, 255));
        jButton34.setForeground(new java.awt.Color(255, 231, 255));
        jButton34.setText("jButton1");
        getContentPane().add(jButton34);

        jButton35.setText("jButton1");
        getContentPane().add(jButton35);

        jButton36.setBackground(new java.awt.Color(255, 204, 255));
        jButton36.setForeground(new java.awt.Color(255, 231, 255));
        jButton36.setText("jButton1");
        getContentPane().add(jButton36);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GameWindow().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    // End of variables declaration//GEN-END:variables
}
