
import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author julie
 */
public class GameWindow extends javax.swing.JFrame {
    private Board board;
    private Knight knight;
    private javax.swing.JButton[][] buttons;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GameWindow.class.getName());

    /**
     * Creates new form GameWindow
     */
    public GameWindow() {
        initComponents();

        board = new Board(6, 6);
        knight = new Knight(0, 0);

        board.turnOff(0, 0);

        initButtonsArray();
        updateBoardUI();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b00 = new javax.swing.JButton();
        b01 = new javax.swing.JButton();
        b02 = new javax.swing.JButton();
        b03 = new javax.swing.JButton();
        b04 = new javax.swing.JButton();
        b05 = new javax.swing.JButton();
        b10 = new javax.swing.JButton();
        b11 = new javax.swing.JButton();
        b12 = new javax.swing.JButton();
        b13 = new javax.swing.JButton();
        b14 = new javax.swing.JButton();
        b15 = new javax.swing.JButton();
        b20 = new javax.swing.JButton();
        b21 = new javax.swing.JButton();
        b22 = new javax.swing.JButton();
        b23 = new javax.swing.JButton();
        b24 = new javax.swing.JButton();
        b25 = new javax.swing.JButton();
        b30 = new javax.swing.JButton();
        b31 = new javax.swing.JButton();
        b32 = new javax.swing.JButton();
        b33 = new javax.swing.JButton();
        b34 = new javax.swing.JButton();
        b35 = new javax.swing.JButton();
        b40 = new javax.swing.JButton();
        b41 = new javax.swing.JButton();
        b42 = new javax.swing.JButton();
        b43 = new javax.swing.JButton();
        b44 = new javax.swing.JButton();
        b45 = new javax.swing.JButton();
        b50 = new javax.swing.JButton();
        b51 = new javax.swing.JButton();
        b52 = new javax.swing.JButton();
        b53 = new javax.swing.JButton();
        b54 = new javax.swing.JButton();
        b55 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(6, 6));

        b00.setBackground(new java.awt.Color(255, 204, 255));
        b00.setForeground(new java.awt.Color(255, 231, 255));
        b00.setText("jButton1");
        b00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b00ActionPerformed(evt);
            }
        });
        getContentPane().add(b00);

        b01.setText("jButton1");
        getContentPane().add(b01);

        b02.setBackground(new java.awt.Color(255, 204, 255));
        b02.setForeground(new java.awt.Color(255, 231, 255));
        b02.setText("jButton1");
        getContentPane().add(b02);

        b03.setText("jButton1");
        b03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b03ActionPerformed(evt);
            }
        });
        getContentPane().add(b03);

        b04.setBackground(new java.awt.Color(255, 204, 255));
        b04.setForeground(new java.awt.Color(255, 231, 255));
        b04.setText("jButton1");
        getContentPane().add(b04);

        b05.setText("jButton1");
        getContentPane().add(b05);

        b10.setText("jButton1");
        getContentPane().add(b10);

        b11.setBackground(new java.awt.Color(255, 204, 255));
        b11.setForeground(new java.awt.Color(255, 231, 255));
        b11.setText("jButton1");
        getContentPane().add(b11);

        b12.setText("jButton1");
        getContentPane().add(b12);

        b13.setBackground(new java.awt.Color(255, 204, 255));
        b13.setForeground(new java.awt.Color(255, 231, 255));
        b13.setText("jButton1");
        getContentPane().add(b13);

        b14.setText("jButton1");
        getContentPane().add(b14);

        b15.setBackground(new java.awt.Color(255, 204, 255));
        b15.setForeground(new java.awt.Color(255, 231, 255));
        b15.setText("jButton1");
        getContentPane().add(b15);

        b20.setBackground(new java.awt.Color(255, 204, 255));
        b20.setForeground(new java.awt.Color(255, 231, 255));
        b20.setText("jButton1");
        getContentPane().add(b20);

        b21.setText("jButton1");
        getContentPane().add(b21);

        b22.setBackground(new java.awt.Color(255, 204, 255));
        b22.setForeground(new java.awt.Color(255, 231, 255));
        b22.setText("jButton1");
        getContentPane().add(b22);

        b23.setText("jButton1");
        getContentPane().add(b23);

        b24.setBackground(new java.awt.Color(255, 204, 255));
        b24.setForeground(new java.awt.Color(255, 231, 255));
        b24.setText("jButton1");
        getContentPane().add(b24);

        b25.setText("jButton1");
        getContentPane().add(b25);

        b30.setText("jButton1");
        getContentPane().add(b30);

        b31.setBackground(new java.awt.Color(255, 204, 255));
        b31.setForeground(new java.awt.Color(255, 231, 255));
        b31.setText("jButton1");
        getContentPane().add(b31);

        b32.setText("jButton1");
        getContentPane().add(b32);

        b33.setBackground(new java.awt.Color(255, 204, 255));
        b33.setForeground(new java.awt.Color(255, 231, 255));
        b33.setText("jButton1");
        getContentPane().add(b33);

        b34.setText("jButton1");
        getContentPane().add(b34);

        b35.setBackground(new java.awt.Color(255, 204, 255));
        b35.setForeground(new java.awt.Color(255, 231, 255));
        b35.setText("jButton1");
        getContentPane().add(b35);

        b40.setBackground(new java.awt.Color(255, 204, 255));
        b40.setForeground(new java.awt.Color(255, 231, 255));
        b40.setText("jButton1");
        getContentPane().add(b40);

        b41.setText("jButton1");
        getContentPane().add(b41);

        b42.setBackground(new java.awt.Color(255, 204, 255));
        b42.setForeground(new java.awt.Color(255, 231, 255));
        b42.setText("jButton1");
        getContentPane().add(b42);

        b43.setText("jButton1");
        getContentPane().add(b43);

        b44.setBackground(new java.awt.Color(255, 204, 255));
        b44.setForeground(new java.awt.Color(255, 231, 255));
        b44.setText("jButton1");
        getContentPane().add(b44);

        b45.setText("jButton1");
        getContentPane().add(b45);

        b50.setText("jButton1");
        getContentPane().add(b50);

        b51.setBackground(new java.awt.Color(255, 204, 255));
        b51.setForeground(new java.awt.Color(255, 231, 255));
        b51.setText("jButton1");
        getContentPane().add(b51);

        b52.setText("jButton1");
        getContentPane().add(b52);

        b53.setBackground(new java.awt.Color(255, 204, 255));
        b53.setForeground(new java.awt.Color(255, 231, 255));
        b53.setText("jButton1");
        getContentPane().add(b53);

        b54.setText("jButton1");
        getContentPane().add(b54);

        b55.setBackground(new java.awt.Color(255, 204, 255));
        b55.setForeground(new java.awt.Color(255, 231, 255));
        b55.setText("jButton1");
        getContentPane().add(b55);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b00ActionPerformed
        allume[0][0] = false;
        b00.setBackground(Color.GRAY);
    }//GEN-LAST:event_b00ActionPerformed

    private void b03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b03ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b03ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GameWindow().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b00;
    private javax.swing.JButton b01;
    private javax.swing.JButton b02;
    private javax.swing.JButton b03;
    private javax.swing.JButton b04;
    private javax.swing.JButton b05;
    private javax.swing.JButton b10;
    private javax.swing.JButton b11;
    private javax.swing.JButton b12;
    private javax.swing.JButton b13;
    private javax.swing.JButton b14;
    private javax.swing.JButton b15;
    private javax.swing.JButton b20;
    private javax.swing.JButton b21;
    private javax.swing.JButton b22;
    private javax.swing.JButton b23;
    private javax.swing.JButton b24;
    private javax.swing.JButton b25;
    private javax.swing.JButton b30;
    private javax.swing.JButton b31;
    private javax.swing.JButton b32;
    private javax.swing.JButton b33;
    private javax.swing.JButton b34;
    private javax.swing.JButton b35;
    private javax.swing.JButton b40;
    private javax.swing.JButton b41;
    private javax.swing.JButton b42;
    private javax.swing.JButton b43;
    private javax.swing.JButton b44;
    private javax.swing.JButton b45;
    private javax.swing.JButton b50;
    private javax.swing.JButton b51;
    private javax.swing.JButton b52;
    private javax.swing.JButton b53;
    private javax.swing.JButton b54;
    private javax.swing.JButton b55;
    // End of variables declaration//GEN-END:variables

    private void initButtonsArray() {
        buttons = new javax.swing.JButton[][]{
            {b00, b01, b02, b03, b04, b05},
            {b10, b11, b12, b13, b14, b15},
            {b20, b21, b22, b23, b24, b25},
            {b30, b31, b32, b33, b34, b35},
            {b40, b41, b42, b43, b44, b45},
            {b50, b51, b52, b53, b54, b55}
        };
    }


    private void updateBoardUI() {
        for (int i = 0; i < 6; i++) {
            for (int j = 0; j < 6; j++) {

                if (board.isLit(i, j)) {
                    buttons[i][j].setBackground(Color.PINK);
                } else {
                    buttons[i][j].setBackground(Color.GRAY);
                }
            }
        }

        // Cavalier en bleu
        buttons[knight.getRow()][knight.getCol()].setBackground(Color.BLUE);
    }

}
